import type { WebsiteScanResult, Finding, Severity } from "@/lib/scanner/types";
import type { PortScanResult } from "@/lib/scanner/port-types";

interface FileHashReportData {
  fileName: string;
  fileSize: number;
  hashes: Record<string, string>;
  verified: boolean | null;
}

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low", "informational"];

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1073741824) return `${(bytes / 1048576).toFixed(1)} MB`;
  return `${(bytes / 1073741824).toFixed(1)} GB`;
}

function severityColor(severity: Severity): string {
  switch (severity) {
    case "critical": return "#ef4444";
    case "high": return "#f97316";
    case "medium": return "#eab308";
    case "low": return "#3b82f6";
    case "informational": return "#6b7280";
  }
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function reportHeader(title: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(title)} — CyberYoshi Report</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1a1a1a; padding: 40px; max-width: 900px; margin: 0 auto; line-height: 1.5; }
  .brand { display: flex; align-items: center; gap: 10px; margin-bottom: 8px; }
  .brand h1 { font-size: 14px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; color: #4f46e5; }
  .title { font-size: 24px; font-weight: 700; margin-bottom: 4px; }
  .meta { font-size: 13px; color: #6b7280; margin-bottom: 32px; }
  .section { margin-bottom: 28px; }
  .section-title { font-size: 16px; font-weight: 600; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px; margin-bottom: 14px; }
  .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin-bottom: 20px; }
  .stat-box { border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px; text-align: center; }
  .stat-value { font-size: 28px; font-weight: 700; }
  .stat-label { font-size: 12px; color: #6b7280; margin-top: 2px; }
  .finding { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; margin-bottom: 10px; }
  .finding-header { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: 600; color: #fff; }
  .finding-title { font-size: 14px; font-weight: 600; }
  .finding-desc { font-size: 13px; color: #374151; margin-bottom: 4px; }
  .finding-evidence { font-size: 12px; font-family: monospace; background: #f3f4f6; padding: 6px 8px; border-radius: 4px; margin-bottom: 4px; word-break: break-all; }
  .finding-rec { font-size: 12px; color: #6b7280; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { background: #f9fafb; text-align: left; padding: 8px 10px; border-bottom: 2px solid #e5e7eb; font-weight: 600; }
  td { padding: 8px 10px; border-bottom: 1px solid #e5e7eb; }
  .hash-row { margin-bottom: 10px; }
  .hash-label { font-size: 12px; font-weight: 600; color: #6b7280; margin-bottom: 2px; }
  .hash-value { font-family: monospace; font-size: 12px; word-break: break-all; background: #f3f4f6; padding: 6px 8px; border-radius: 4px; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>`;
}

function reportFooter(): string {
  return `
<div style="margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center;">
  Generated by CyberYoshi v0.1.0 — Cybersecurity Toolkit
</div>
</body></html>`;
}

function findingsHtml(findings: Finding[]): string {
  if (findings.length === 0) return '<p style="font-size: 13px; color: #6b7280;">No findings.</p>';

  const sorted = [...findings].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );

  return sorted
    .map(
      (f) => `
    <div class="finding">
      <div class="finding-header">
        <span class="badge" style="background: ${severityColor(f.severity)}">${f.severity.toUpperCase()}</span>
        <span class="finding-title">${escapeHtml(f.title)}</span>
      </div>
      <div class="finding-desc">${escapeHtml(f.description)}</div>
      ${f.evidence ? `<div class="finding-evidence">${escapeHtml(f.evidence)}</div>` : ""}
      <div class="finding-rec"><strong>Recommendation:</strong> ${escapeHtml(f.recommendation)}</div>
    </div>`
    )
    .join("");
}

export function generateWebsiteReport(data: WebsiteScanResult): string {
  const sortedFindings = [...data.findings].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );
  const counts = SEVERITY_ORDER.map(
    (s) => `${s.charAt(0).toUpperCase() + s.slice(1)}: ${sortedFindings.filter((f) => f.severity === s).length}`
  ).join(" | ");

  let html = reportHeader("Website Security Report");

  html += `
<div class="brand"><span style="font-size:20px;">🛡</span><h1>CyberYoshi</h1></div>
<div class="title">Website Security Report</div>
<div class="meta">Target: ${escapeHtml(data.url)} &bull; Scanned: ${escapeHtml(data.scannedAt)}</div>

<div class="stat-grid">
  <div class="stat-box"><div class="stat-value">${data.score}</div><div class="stat-label">Security Score / 100</div></div>
  <div class="stat-box"><div class="stat-value">${data.findings.length}</div><div class="stat-label">Findings</div></div>
  <div class="stat-box"><div class="stat-value">${data.crawl.pagesVisited.length}</div><div class="stat-label">Pages Crawled</div></div>
  <div class="stat-box"><div class="stat-value">${data.crawl.brokenLinks.length}</div><div class="stat-label">Broken Links</div></div>
</div>
<p style="font-size: 13px; color: #6b7280; margin-bottom: 20px;">${counts}</p>

<div class="section">
  <div class="section-title">Security Findings</div>
  ${findingsHtml(data.findings)}
</div>

<div class="section">
  <div class="section-title">Crawl Results</div>
  <table>
    <thead><tr><th>Page</th></tr></thead>
    <tbody>${data.crawl.pagesVisited.map((p) => `<tr><td style="font-size:12px;word-break:break-all;">${escapeHtml(p)}</td></tr>`).join("")}</tbody>
  </table>
</div>`;

  if (data.technologies.technologies.length > 0) {
    html += `
<div class="section">
  <div class="section-title">Detected Technologies</div>
  <p style="font-size: 13px;">${data.technologies.technologies.map((t) => escapeHtml(t.name)).join(", ")}</p>
</div>`;
  }

  if (data.cookies.cookies.length > 0) {
    html += `
<div class="section">
  <div class="section-title">Cookies</div>
  <table>
    <thead><tr><th>Name</th><th>Secure</th><th>HttpOnly</th><th>SameSite</th></tr></thead>
    <tbody>${data.cookies.cookies.map((c) => `<tr><td style="font-family:monospace">${escapeHtml(c.name)}</td><td>${c.secure ? "Yes" : "No"}</td><td>${c.httpOnly ? "Yes" : "No"}</td><td>${escapeHtml(c.sameSite || "None")}</td></tr>`).join("")}</tbody>
  </table>
</div>`;
  }

  html += reportFooter();
  return html;
}

export function generatePortReport(data: PortScanResult): string {
  const sortedPorts = [...data.ports].sort((a, b) => {
    const order = { open: 0, filtered: 1, closed: 2, error: 3 };
    return order[a.status] - order[b.status] || a.port - b.port;
  });

  let html = reportHeader("Port Scan Report");

  html += `
<div class="brand"><span style="font-size:20px;">🛡</span><h1>CyberYoshi</h1></div>
<div class="title">Port Scan Report</div>
<div class="meta">Target: ${escapeHtml(data.target)} &bull; Scanned: ${escapeHtml(data.scannedAt)}</div>

<div class="stat-grid">
  <div class="stat-box"><div class="stat-value" style="color:#22c55e">${data.openPorts}</div><div class="stat-label">Open Ports</div></div>
  <div class="stat-box"><div class="stat-value">${data.closedPorts}</div><div class="stat-label">Closed Ports</div></div>
  <div class="stat-box"><div class="stat-value">${data.filteredPorts}</div><div class="stat-label">Filtered Ports</div></div>
  <div class="stat-box"><div class="stat-value">${data.ports.length}</div><div class="stat-label">Total Scanned</div></div>
</div>

<div class="section">
  <div class="section-title">Port Results</div>
  <table>
    <thead><tr><th>Port</th><th>Status</th><th>Service</th><th>Risk</th><th>Details</th></tr></thead>
    <tbody>
      ${sortedPorts
        .map(
          (p) => `<tr>
            <td style="font-family:monospace;font-weight:600">${p.port}</td>
            <td><span class="badge" style="background:${p.status === "open" ? "#ef4444" : p.status === "filtered" ? "#6b7280" : "#9ca3af"}">${p.status.toUpperCase()}</span></td>
            <td>${escapeHtml(p.service)}</td>
            <td>${p.status === "open" ? p.risk : "—"}</td>
            <td style="font-size:12px;color:#6b7280">${p.status === "open" ? escapeHtml(p.riskReason) : ""}</td>
          </tr>`
        )
        .join("")}
    </tbody>
  </table>
</div>`;

  html += reportFooter();
  return html;
}

export function generateFileHashReport(data: FileHashReportData): string {
  let html = reportHeader("File Hash Report");

  html += `
<div class="brand"><span style="font-size:20px;">🛡</span><h1>CyberYoshi</h1></div>
<div class="title">File Hash Report</div>
<div class="meta">File: ${escapeHtml(data.fileName)} &bull; Size: ${formatSize(data.fileSize)}</div>

<div class="stat-grid">
  <div class="stat-box"><div class="stat-value" style="font-size:18px">${Object.keys(data.hashes).length}</div><div class="stat-label">Hash Algorithms</div></div>
  <div class="stat-box"><div class="stat-value" style="color:${data.verified === true ? "#22c55e" : data.verified === false ? "#ef4444" : "#6b7280"};font-size:18px">${data.verified === true ? "Verified" : data.verified === false ? "Not Verified" : "N/A"}</div><div class="stat-label">Verification</div></div>
</div>

<div class="section">
  <div class="section-title">Generated Hashes</div>
  ${Object.entries(data.hashes)
    .map(
      ([algo, hash]) => `
    <div class="hash-row">
      <div class="hash-label">${algo.toUpperCase()}</div>
      <div class="hash-value">${escapeHtml(hash)}</div>
    </div>`
    )
    .join("")}
</div>`;

  html += reportFooter();
  return html;
}

export function openReport(html: string): void {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  window.open(url, "_blank");
}

export function downloadReport(html: string, filename: string): void {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
